# Generated by Django 4.1.5 on 2023-02-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_keeper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='income', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='money_keeper_app.expensetype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='money_keeper_app.incometype'),
        ),
    ]
